workflows:
  default-workflow:
    name: Build Ticket App
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      groups:
        - shorebird_token # Create this group in Codemagic UI and add SHOREBIRD_TOKEN
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
      - name: Build iOS IPA
        script: |
          # The following script works only if you have set up code signing in Codemagic
          flutter build ipa --release --no-codesign
      - name: Shorebird Release
        script: |
          # Use the provided SHOREBIRD_TOKEN in Codemagic environment variables
          shorebird login:ci $SHOREBIRD_TOKEN
          shorebird release android --no-codesign
          # shorebird release ios --no-codesign # Needs Mac, Codemagic m2 has it.

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/ipa/*.app
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - sarthou@gmail.com # Based on git config
